import Head from 'next/head';
import Link from 'next/link';
import Banner from '../components/Banner';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <Banner />
      </main>

      <footer>
        <div className='text-center'>
          Copyright <Link href={'/'}>Ovikkhon</Link> @2022
        </div>
      </footer>
    </div>
  );
}
