import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-bodyBg min-h-screen flex items-center justify-center'>
        <h1 className='text-3xl'>Welcome to Ovikkhon</h1>
      </main>

      <footer>
        <div className='text-center'>
          Copyright <Link href={'/'}>Ovikkhon</Link> @2022
        </div>
      </footer>
    </div>
  );
}
